# All fields are optional, unless stated otherwise
host: example.com # defaults to localhost
port: 9090 # defaults to 9090
log_level: "debug" # defaults to 'info', other options are 'warn' and 'error'
web_admin: true # Enable HTTP-api for inspection -- to retrieve pipelines and logs
web_admin_user: 'admin' # Basic auth user for inspection API. Defaults to "admin"
web_admin_password: '' # Basic auth user for inspection API. Empty string (disabled) by default
# SSL config: (optional, but recommended, unless you're using a reverse proxy)
ssl:
  cert_file_path: "./your/certfile/path/fullchain.pem"
  key_file_path: "/your/keyfile/path/privkey.pem"
projects:
  your_project_name:
    git_provider: gitea # defaults to "github"
    repo: "username/reponame" # REQUIRED repository full name, as displayed in the URL
    # please notice, it may be safer to keep secret and authorization tokens 
    # in env variables, depending on your application deployment and setup
    secret: "YourSecretGoesHere" # your secret, used to sign the payload and validate it
    authorization: "JghYTd" # post authorization header contents, to authorize the incoming request
    actions:
      - on: push # defaults to "push", use "*" to handle any incoming event
        branch: master # defaults to master
        user: www-data # user from which action will be run
        cwd: "/var/www/yourproject" # root dir in which action will be run
        # each action MUST have either a script or run field (but not both):
        # To run a script:
        script: |
          git fetch && git reset --hard origin/master
          npm ci
          npm run build
        # Or to execute a script or program:
        # run: ["node", "--version"]
 # Defaults to "actions.sqlite3", use empty string or null to disable actions result storage
actions_db_file: "actions.sqlite3"
logs_db_file: "logs.sqlite3" # Storage of application logs, disabled by default