host: "localhost"
port: 9090
log_file: "deploy.log"
log_level: "debug"
projects:
  staticus:
    git_provider: gitea
    repo: "religiosa/staticus"
    cwd: "/var/www/staticus"
    actions:
      - on: push
        branch: master
        user: www-data
        run: ["node", "--version"]
        # script: >
        #   git fetch && git reset --hard origin/master
        #   npm ci
        #   npm run build
