host: example.com # defaults to localhost
port: 9090 # OPTIONAL, defaults to 9090
log_level: "debug" # OPTIONAL, defaults to 'info', other options are 'warn' and 'error'
# Optional (but recommended, unless you're using a reverse proxy): SSL config:
ssl:
  cert_file_path: "./your/certfile/path/fullchain.pem"
  key_file_path: "/your/keyfile/path/privkey.pem"
projects:
  your_project_name:
    git_provider: gitea
    repo: "username/reponame" # repository full name, as displayed in the URL
    actions:
      - on: push # OPTIONAL defaults to "push", use "*" to handle any incoming event
        branch: master # OPTIONAL  defaults to master
        user: www-data # OPTIONAL user from which action will be run
        # please notice, it may be safer to keep secret and authorization tokens 
        # in env variables, depending on your application
        secret: "YourSecretGoesHere" # OPTIONAL your secret, used to sign the payload and validate it
        authorization: "JghYTd" # OPTIONAL post authorization header contents, to authorize the incoming request
        cwd: "/var/www/yourproject" # OPTIONAL root dir in which action will be run
        # To run a script:
        script: |
          git fetch && git reset --hard origin/master
          npm ci
          npm run build
        # Or to execute a script or program:
        # run: ["node", "--version"]
# TODO remove all that and log directly into SQLite instance instead of a file
log_file: "deploy.log"
actions_output_dir: "actions_output"