host: "localhost"
port: 9090
log_file: "deploy.log"
log_level: "debug"
actions_output_dir: "actions_output"
max_output_files: 10_000
projects:
  staticus:
    git_provider: gitea
    repo: "username/reponame" # repository full name, as displayed in the URL
    actions:
      - on: push
        branch: master
        user: www-data # user from which action will be run
        cwd: "/var/www/staticus" # root dir in which action will be run, optional
        # To run a script:
        script: |
          git fetch && git reset --hard origin/master
          npm ci
          npm run build
        # Or to execute a script or program:
        # run: ["node", "--version"]
